# user acceptance test env resources
server:
  port: 18888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jungle93/spring-cloud-config-repo.git
          basedir: /user-acceptance-test
  application:
    name: application-config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/