# development env resources
server:
  port: 8801
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka-client-provider
management:
  endpoint:
    health:
      enabled: true
